[build-system]
requires = [
    "scikit-build-core>=0.11"
]
build-backend = "scikit_build_core.build"


[project]
name = "gpumetric"
version = "0.1.1"

description = "Lightweight NVIDIA GPU metrics library for Python"

readme = "README.md"

requires-python = ">=3.10,<3.16"

authors = [
    { name = "Max Agateff" }
]

license = { text = "GNU General Public License v3.0" }

classifiers = [
    "Development Status :: 3 - Alpha",

    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",

    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",

    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",

    "Programming Language :: C",

    "Operating System :: POSIX :: Linux",

    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: System :: Monitoring",
]


[project.urls]
Homepage = "https://github.com/maxagateff/GPUMetric"
Repository = "https://github.com/maxagateff/GPUMetric"
Documentation = "https://github.com/maxagateff/GPUMetric/blob/master/docs/DOCS.md"
Issues = "https://github.com/maxagateff/GPUMetric/issues"
PyPI = "https://pypi.org/project/gpumetric/"
License = "https://github.com/maxagateff/GPUMetric/blob/master/LICENSE"


[tool.scikit-build]
wheel.packages = ["src/gpumetric"]


[tool.scikit-build.cmake]
build-type = "Release"
